apiVersion: v1
kind: Service
metadata:
  name: context-proxy-service
spec:
  selector:
    app: context-proxy-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 4400
      targetPort: 4400