apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sunbirdrc
  name: certificate-api
  labels:
    app: certificate-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: certificate-api
  template:
    metadata:
      name: certificate-api
      labels:
        app: certificate-api
    spec:
      containers:
        - name: certificate-api
          image: srprasanna/sunbird-rc-certificate-api:v0.0.13-1
          imagePullPolicy: Always
          ports:
            - containerPort: 8078
          env:
            - name: PORT
              value: "8078"
            - name: QR_TYPE
              value: URL
            - name: CERTIFICATE_DOMAIN_URL
              valueFrom:
                configMapKeyRef: # populate from a ConfigMap
                  name: donor-registry-config   # ... with this name
                  key: CERTIFICATE_DOMAIN_URL
          resources:
            requests:
              cpu: 1000m
              memory: 2G
      restartPolicy: Always
